### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by Graig864** [FundamentalFrequency/LMN-3-Build-Guide#6]
Need substitute originals not their

**Comment by stonepreston** [comment]
Its the hyperpixel 4 touch version. Guess sparkfun does not carry that anymore. [Here](https://shop.pimoroni.com/en-us/products/hyperpixel-4) is the screen on pimoroni. Ill update the table thanks for noticing this.

**Comment by stonepreston** [comment]
Link in build guide has been updated.
