### ISSUE TITLE
Drum Sampler quits LMN 3 program

### ISSUE THREAD

**Issue by tanno1** [FundamentalFrequency/LMN-3-Build-Guide#7]
Hey!
I just finished my build, however when I go to the drum sample and press in on the second encoder, the whole software shuts down. Not sure where to start with debugging this one, if there are any ideas let me know. I added a photo of the contents of my folders all the way  up to a sample pack as well as my .yaml file for one of the kits I made.

As an experiment, I placed one of my kits in the samples area, and I can access that and go through the directory to choose one noise, but that isn't exactly ideal. I will look into this more on my own as well and update this issue if I find any answers. If anyone doesn't know the solution, recommendations on where I can look are great as well.

Thanks
tanno

![image](https://github.com/FundamentalFrequency/LMN-3-Build-Guide/assets/94481731/f57ff475-7095-4f39-ba87-174bda8a9284)

![image](https://github.com/FundamentalFrequency/LMN-3-Build-Guide/assets/94481731/8ecccedd-b2a8-4629-a8e5-788b5bb14c09)

**Comment by stonepreston** [comment]
can you see if anything is in the log file (should be in the LMN-3 config directory somewhere)

**Comment by tanno1** [comment]
Yes, there is a ton of stuff here. Mainly consisting of Controller [#]: 1, or Note on D3 and Note off D3 (or other notes). Should I be seeing what is at the top or the bottom of the file?

**Comment by tanno1** [comment]
Here is what I see at the bottom of log.txt before having opened the drum sampler:
![image](https://github.com/FundamentalFrequency/LMN-3-Build-Guide/assets/94481731/40f5b009-500e-47a5-98d5-a6d3f21cf2df)
![image](https://github.com/FundamentalFrequency/LMN-3-Build-Guide/assets/94481731/7450e1d4-62db-46ac-beb8-d5020deb05c5)

After I crash the program opening drum sampler and open up log.txt again, this is what I see:
![image](https://github.com/FundamentalFrequency/LMN-3-Build-Guide/assets/94481731/e78f4ff2-5fc8-4375-b718-4e269387ee22)

**Comment by stonepreston** [comment]
alright doesnt look like anything helpful in the log then. Can you try starting the LMN-3 application in its own terminal window (ie run ./LMN-3 yourself in the terminal, not on startup) and see if anything helpful in printed in the terminal window after the crash

**Comment by tanno1** [comment]
Here is what it looks like after starting it from the terminal
![image](https://github.com/FundamentalFrequency/LMN-3-Build-Guide/assets/94481731/b528ac88-4106-4ee9-8427-3d107a31fcdb)
![image](https://github.com/FundamentalFrequency/LMN-3-Build-Guide/assets/94481731/950f5e88-5785-4fd0-8bd9-4da85199c53a)

And here is what I get when I open drum sampler and crash it: 
![image](https://github.com/FundamentalFrequency/LMN-3-Build-Guide/assets/94481731/5977972b-0113-4976-9706-8cabcaa2527e)

**Comment by stonepreston** [comment]
ok so youve got some badly formatted yaml in your drum kit somewhere, run your yaml through something like [yamllint](https://www.yamllint.com/) and it should point you to what could be wrong

**Comment by tanno1** [comment]
Ok got it, first time working with yaml stuff. Thanks! Has anyone started working on a JUCE application to make this easier?
